# Generated by Django 5.1.2 on 2024-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="desc",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="destination",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
        migrations.AddField(
            model_name="destination",
            name="name",
            field=models.CharField(default="Unnamed Destination", max_length=100),
        ),
        migrations.AddField(
            model_name="destination",
            name="offer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="destination",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="destination",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
