# Generated by Django 5.1.2 on 2024-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travello", "0002_destination_desc_destination_img_destination_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="price",
            field=models.IntegerField(),
        ),
    ]
